### ISSUE TITLE
게시글 기능 추가 및 오류 개선- 전율택

### ISSUE THREAD

**Issue by TwinOgre** [devCommunity13134/devCom#31]
#### 게시글 검색
- [x] 네비바 통합검색
통합검색 페이지 생성(searchList)
- [x] 카테고리별 상세검색 

#### 게시글 목록
- [x] 조회수별, 좋아요별 정렬 버튼 기능 구현
#### 게시글 상세
- [x] 게시글 상세 삭제 버튼 클릭 시 자바스크립트 안내 창 구현
- [x] 목록으로 가는 버튼 생성
#### index
- [x] 메인화면에 게시글 글쓰기 버튼 추가

### 보류
- 게시글 생성 시 마크다운

**Comment by DooHwanKim92** [comment]
이슈 해결 시 close 부탁드려용~
